# Generated by Django 3.0.7 on 2020-06-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200620_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/profile_pics/default.jpg', upload_to='profile_pics'),
        ),
    ]
